# Generated by Django 5.0 on 2024-01-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
    ]
