# Generated by Django 5.0 on 2024-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_vacancies', '0003_remove_vacancy_salary_vacancy_salary_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
