# Generated by Django 5.0 on 2024-01-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCountAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaCountProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('vacancy_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaSalaryAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaSalaryProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('average_salary', models.IntegerField()),
            ],
        ),
    ]
