# Generated by Django 5.0 on 2024-01-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacountall',
            name='vacancy_count',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='areacountprof',
            name='vacancy_count',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
